# Generated by Django 6.1.1 on 2026-10-06 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WasteType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name_id", models.CharField(max_length=255)),
                (
                    "emission_factor_kgco2e_per_kg",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                ("emission_factor_source", models.TextField(blank=True, default="")),
                ("emission_factor_note", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WasteTypeAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("alias_normalized", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "waste_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="core.wastetype",
                    ),
                ),
            ],
        ),
    ]
