# Generated by Django 6.1.1 on 2026-10-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_wastetype_wastetypealias"),
        ("deposits", "0001_initial"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposits",
                to="ingestion.upload",
            ),
        ),
        migrations.AddField(
            model_name="deposit",
            name="waste_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deposits",
                to="core.wastetype",
            ),
        ),
    ]
