# Generated by Django 6.1.1 on 2026-10-06 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_wastetype_wastetypealias"),
        ("deposits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("kind", models.CharField(choices=[("llm", "LLM"), ("ocr", "OCR")], max_length=10)),
                ("response", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(choices=[("image", "Image"), ("text", "Text")], max_length=10),
                ),
                ("source_sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("image_sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("raw_text", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_sampah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="core.banksampah",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Extraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("vision", "Vision"),
                            ("ocr_text", "OCR Text"),
                            ("hybrid", "Hybrid"),
                            ("text", "Text"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=100)),
                ("ocr_engine", models.CharField(blank=True, max_length=20, null=True)),
                ("prompt_version", models.CharField(max_length=50)),
                ("schema_version", models.CharField(max_length=50)),
                ("raw_response", models.JSONField(default=dict)),
                ("ocr_lines", models.JSONField(blank=True, null=True)),
                ("page_meta", models.JSONField(default=dict)),
                ("latency_ms", models.IntegerField(default=0)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("from_cache", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extractions",
                        to="ingestion.upload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content_type", models.CharField(default="image/jpeg", max_length=50)),
                ("data", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="ingestion.upload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtractedRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("row_index", models.IntegerField()),
                ("tanggal_raw", models.CharField(blank=True, max_length=100, null=True)),
                ("nama_raw", models.CharField(blank=True, max_length=255, null=True)),
                ("jenis_raw", models.CharField(blank=True, max_length=255, null=True)),
                ("berat_raw", models.CharField(blank=True, max_length=100, null=True)),
                ("satuan_raw", models.CharField(blank=True, max_length=50, null=True)),
                ("evidence_text", models.TextField(default="")),
                ("date_is_repeat", models.BooleanField(default=False)),
                ("llm_confidence", models.FloatField(default=0.0)),
                ("y_min", models.FloatField(blank=True, null=True)),
                ("y_max", models.FloatField(blank=True, null=True)),
                ("source_lines", models.JSONField(blank=True, null=True)),
                ("tanggal", models.DateField(blank=True, null=True)),
                (
                    "weight_kg",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                ("flags", models.JSONField(default=list)),
                ("score", models.FloatField(blank=True, null=True)),
                ("route", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("saved", "Saved"),
                            ("rejected", "Rejected"),
                            ("reverted", "Reverted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("human_edited", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deposit",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extracted_row",
                        to="deposits.deposit",
                    ),
                ),
                (
                    "nasabah",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extracted_rows",
                        to="core.nasabah",
                    ),
                ),
                (
                    "waste_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extracted_rows",
                        to="core.wastetype",
                    ),
                ),
                (
                    "extraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="ingestion.extraction",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="ingestion.upload",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("extraction", "row_index"), name="unique_row_per_extraction"
                    )
                ],
            },
        ),
    ]
